jobs:
  test_lint:
    docker:
      - image: circleci/node:12.9.0
    steps:
      - checkout
      - run:
          name: Setup
          command: npm install
      # - run:
      #     name: Build
      #     command: npm run build
      - run:
          name: Lint
          command: npm run lint

workflows:
  version: 2
  build:
    jobs:
      - test_lint
