version: 2.1
jobs:
  test-and-build:
    docker:
      - image: cimg/node:16.4.1
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Test
          command: npm run test
      - run:
          name: Build
          command: npm run build
  semantic_release: #only running if added to workflow jobs
    docker:
      - image: cimg/node:16.4.1
    steps:
      - checkout
      - run:
          name: Install 'semantic-release' modules
          command: |
            npm i -g @stackr23/conventional-changelog-config 2> /dev/null && npm i -g @stackr23/preset-conventional-changelog 2> /dev/null
            npm i --no-save semantic-release-cli @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/git @semantic-release/github @semantic-release/npm @semantic-release/release-notes-generator
      - run:
          name: Run 'semantic-release'
          command: npx semantic-release

workflows:
  test:
    jobs:
      - test-and-build
