version: 2.1
workflows:
  build:
    jobs:
      - build:
          matrix:
            parameters:
              os: [linux, macos]
              node_version: [6, 8, 10]
          name: build-<< matrix.os >>-<< matrix.node_version >>
      - test:
          matrix:
            parameters:
              os: [linux, macos]
              node_version: [6, 8, 10]
          name: test-<< matrix.os >>-<< matrix.node_version >>
          # Templated dependency:
          # "Each `test` job depends on its corresponding `build` job"
          requires:
            - build-<< matrix.os >>-<< matrix.node_version >>
