version: 2.1
orbs:
  node: circleci/node@4.5.1
workflows:
  matrix-tests:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - 13.11.0
                - 12.16.0
                - 10.19.0
