name: Test and Lint
on:
  push:
    branches:
      - 'develop'
      - 'feat/**'
      - 'fix/**'
    tags-ignore:
      - '**'
jobs:
  test_and_lint:
    name: Testing with NodeJS v${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: ['12', '13', '14']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run karma
